"""Default (OSS) TensorFlow wheel version suffix data."""

WHEEL_VERSION_SUFFIX = ""
SEMANTIC_WHEEL_VERSION_SUFFIX = ""  # ppc64le: stub

VERSION_SUFFIX = WHEEL_VERSION_SUFFIX
SEMANTIC_VERSION_SUFFIX = SEMANTIC_WHEEL_VERSION_SUFFIX
